# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 22:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenebuilder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_name', models.CharField(max_length=32)),
                ('scene_background', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateGrid',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scene_grid', models.CharField(max_length=640)),
                ('parent_scene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenebuilder.Scene')),
            ],
        ),
        migrations.AlterField(
            model_name='map',
            name='map_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AddField(
            model_name='scene',
            name='parent_map',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenebuilder.Map'),
        ),
    ]
