# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 05:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenebuilder', '0003_map_map_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='map_path',
            field=models.CharField(max_length=128),
        ),
    ]
