# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 22:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(default=datetime.datetime(2017, 5, 7, 22, 34, 28, 243683, tzinfo=utc), verbose_name='published on')),
                ('scene_name', models.CharField(default='scene', max_length=64)),
                ('scene_author', models.CharField(default='anonymous', max_length=16)),
            ],
        ),
    ]
