# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 23:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_scene'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scene',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 5, 7, 23, 6, 24, 891871, tzinfo=utc), verbose_name='published on'),
        ),
    ]
